name: API CHECKS

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Create .env File
        run: |
          cat <<EOF > sellshoes/sellshoes/.env
          EMAIL_HOST_USER=${{ secrets.EMAIL_HOST_USER }}
          EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD }}
          API_KEY=${{ secrets.API_KEY }}
          API_SECRET=${{ secrets.API_SECRET }}          
          EOF

      - name: Startup Services
        run: docker compose up -d

      - name: Await Services
        uses: jakejarvis/wait-action@master
        with:
          time: "5s"

      - name: Show Services Logs
        run: docker compose logs

      - name: Run All Migrations
        run: docker compose exec -T api poetry run python manage.py migrate
        
      - name: Run Unit Tests
        run: docker compose exec api pytest -v
#TODO: Uncomment this block to run API schemathesis tests
    #   - name: Run API Tests
    #     run: docker compose exec api schemathesis run https://127.0.0.1:8000/test/swagger.json --request-tls-verify=false -v

      - name: Shutdown Services
        run: docker compose down -v